// <auto-generated />
using System;
using BulletJournal.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BulletJournal.Core.Migrations
{
    [DbContext(typeof(JournalContext))]
    partial class JournalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BulletJournal.Models.Collection.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("BulletJournal.Models.Index", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Index");
                });

            modelBuilder.Entity("BulletJournal.Models.Journal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IndexId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndexId");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("BulletJournal.Models.Page", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("JournalId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("BulletJournal.Models.Collection.Collection", b =>
                {
                    b.HasOne("BulletJournal.Models.Page", null)
                        .WithMany("Collections")
                        .HasForeignKey("PageId");
                });

            modelBuilder.Entity("BulletJournal.Models.Journal", b =>
                {
                    b.HasOne("BulletJournal.Models.Index", "Index")
                        .WithMany()
                        .HasForeignKey("IndexId");

                    b.Navigation("Index");
                });

            modelBuilder.Entity("BulletJournal.Models.Page", b =>
                {
                    b.HasOne("BulletJournal.Models.Journal", null)
                        .WithMany("Pages")
                        .HasForeignKey("JournalId");
                });

            modelBuilder.Entity("BulletJournal.Models.Journal", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("BulletJournal.Models.Page", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
