// <auto-generated />
using System;
using BulletJournal.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulletJournal.Data.Migrations
{
    [DbContext(typeof(BulletJournalContext))]
    [Migration("20221129012204_Timestamp")]
    partial class Timestamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulletJournal.Data.Model.Bullet.BulletEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CollectionId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Signifier")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ParentId");

                    b.ToTable("Bullet", (string)null);
                });

            modelBuilder.Entity("BulletJournal.Data.Model.Collection.CollectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("Collection", (string)null);
                });

            modelBuilder.Entity("BulletJournal.Data.Model.IndexEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("JournalId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JournalId")
                        .IsUnique()
                        .HasFilter("[JournalId] IS NOT NULL");

                    b.ToTable("Index", (string)null);
                });

            modelBuilder.Entity("BulletJournal.Data.Model.JournalEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Journal", (string)null);
                });

            modelBuilder.Entity("BulletJournal.Data.Model.PageEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("JournalId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.ToTable("Page", (string)null);
                });

            modelBuilder.Entity("BulletJournal.Data.Model.TopicEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("IndexId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PageNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IndexId");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("BulletJournal.Data.Model.Bullet.BulletEntity", b =>
                {
                    b.HasOne("BulletJournal.Data.Model.Collection.CollectionEntity", "Collection")
                        .WithMany("Bullets")
                        .HasForeignKey("CollectionId");

                    b.HasOne("BulletJournal.Data.Model.Bullet.BulletEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collection");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.Collection.CollectionEntity", b =>
                {
                    b.HasOne("BulletJournal.Data.Model.PageEntity", "Page")
                        .WithMany("Collections")
                        .HasForeignKey("PageId");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.IndexEntity", b =>
                {
                    b.HasOne("BulletJournal.Data.Model.JournalEntity", "Journal")
                        .WithOne("Index")
                        .HasForeignKey("BulletJournal.Data.Model.IndexEntity", "JournalId");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.PageEntity", b =>
                {
                    b.HasOne("BulletJournal.Data.Model.JournalEntity", "Journal")
                        .WithMany("Pages")
                        .HasForeignKey("JournalId");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.TopicEntity", b =>
                {
                    b.HasOne("BulletJournal.Data.Model.IndexEntity", "Index")
                        .WithMany("Topics")
                        .HasForeignKey("IndexId");

                    b.Navigation("Index");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.Collection.CollectionEntity", b =>
                {
                    b.Navigation("Bullets");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.IndexEntity", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.JournalEntity", b =>
                {
                    b.Navigation("Index");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("BulletJournal.Data.Model.PageEntity", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
